
--
-- Table structure for table `ATIVO`
--

CREATE DATABASE  IF NOT EXISTS `inventory`;
USE `inventory`;

DROP TABLE IF EXISTS `ATIVO`;
CREATE TABLE `ATIVO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NUMERO_SERIE` VARCHAR(50),
  `DESCRICAO` VARCHAR(100) NOT NULL,
  `VALOR` DECIMAL NOT NULL,
  PRIMARY KEY (`ID`)
);
--
-- Dumping data for table `ATIVO`
--
INSERT INTO `ATIVO` VALUES (1, 'ABC1234', 'Meu Modelo Vermelho', 35500),(2, 'AAA1234', 'Minha Moto', 24000);